atenea/urls.py
from django.contrib import admin
from django.urls import path, include
from gestion_almacenes import views, admin
from gestion_almacenes.views import checkout, procesar_compra, eliminar_producto
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/registrar_producto/', views.registrar_producto, name="registrar_producto"),
    path('admin/pedidos_productos/', views.pedidos_productos, name='pedidos_productos'),
    path('admin/', admin.my_admin_site.urls),
    path('', views.index, name="home"),
    path("producto/", include("gestion_almacenes.urls")),
    path('register/', views.register, name="register"),
    path('accounts/login/', views.ClienteLoginView.as_view(), name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('checkout/', checkout, name='checkout'),
    path('checkout/procesar_compra/', procesar_compra, name='procesar_compra'),
    path("pedidos_cliente/",views.pedidos_cliente, name="pedidos_cliente"),
    path('eliminar/<int:producto_id>/', eliminar_producto, name='eliminar_producto'),
    path('', include('gestion_almacenes.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gestion_almacenes/urls.py
from django.urls import path
from . import views


urlpatterns = [
   path('detail/<str:id>/', views.producto_detail, name="detail"),
   path('cesta/<str:id>/', views.anadirAcesta, name="cesta"),
]

gestion_almacenes/models.py
from django.db import models

from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models


class ClienteManager(BaseUserManager):
    def create_user(self, nombre_cliente, email, password=None, **extra_fields):
        if not email:
            raise ValueError('El campo email es obligatorio.')
        email = self.normalize_email(email)
        user = self.model(nombre_cliente=nombre_cliente, email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, nombre_cliente, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(nombre_cliente, email, password, **extra_fields)
    
class Cliente(AbstractBaseUser, PermissionsMixin):
    nombre_cliente = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    direccion_cliente = models.CharField(max_length=150)
    codigo_postal = models.CharField(max_length=10)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = ClienteManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['nombre_cliente']

    def __str__(self):
        return self.nombre_cliente

class Proveedor(models.Model):
    nombre_proveedor = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre_proveedor


class Producto(models.Model):
    referencia = models.CharField(max_length=20)
    # nombre_producto = models.CharField(max_length=100)
    proveedor = models.ForeignKey(Proveedor, on_delete=models.CASCADE)
    cantidad_stock = models.PositiveIntegerField(default=0)
    cantidad_minima_reaprovisionamiento = models.PositiveIntegerField()
    precio = models.PositiveIntegerField(default=0)
    peso_por_unidad = models.FloatField(default=200)
    imagen = models.ImageField(upload_to='media/', blank= True, null= True )


    def __str__(self):
        return self.referencia



class Pedido(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    fecha_hora_pedido = models.DateTimeField()
    TIPO_ENVIO_CHOICES = [
        ('EST', 'Estándar'),
        ('URG', 'Urgente'),
    ]
    tipo_envio = models.CharField(max_length=3, choices=TIPO_ENVIO_CHOICES)
    AGENCIA_TRANSPORTE_CHOICES = [
        ('COR', 'Correos'),
        ('SEU', 'Seur'),
        ('DHL', 'DHL'),
    ]
    agencia_transporte = models.CharField(max_length=3, choices=AGENCIA_TRANSPORTE_CHOICES)
    etiqueta = models.ImageField(upload_to='media/etiquetas/', blank= True, null= True )
    albaran = models.FileField(upload_to='media/albaranes/', blank= True, null= True)
    def __str__(self):
        return f"{self.cliente} - {self.fecha_hora_pedido}"


class PedidoProducto(models.Model):
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField()

    def __str__(self):
        return f"{self.pedido} - {self.producto}"


class Posicion(models.Model):
    TIPO_POSICION_CHOICES = [
        ('PIC', 'Picking'),
        ('STO', 'Stock'),
    ]
    id = models.CharField(max_length=6, primary_key=True)
    tipo_posicion = models.CharField(max_length=3, choices=TIPO_POSICION_CHOICES)
    capacidad = models.PositiveIntegerField()
    unidades_ocupadas = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f"{self.tipo_posicion} - {self.id}"


class ProductoPosicion(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    posicion = models.ForeignKey(Posicion, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.producto} - {self.posicion}"

gestion_almacenes/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Cliente
from .models import Pedido
class FiltroProveedorForm(forms.Form):
    proveedor = forms.ChoiceField(choices=(), required=False, label='Filtrar por proveedor')

    def __init__(self, proveedores, *args, **kwargs):
        super(FiltroProveedorForm, self).__init__(*args, **kwargs)
        self.fields['proveedor'].choices = [('','----')] + [(proveedor, proveedor) for proveedor in proveedores]

class ClienteCreationForm(UserCreationForm):
    class Meta:
        model = Cliente
        fields = ('nombre_cliente', 'email', 'direccion_cliente', 'codigo_postal')


class PedidoFilterForm(forms.Form):
    pedido = forms.ModelChoiceField(queryset=Pedido.objects.all(), required=False, label='Pedido')

gestion_almacenes/views.py
from io import BytesIO
import re
from django.conf import settings
from django.shortcuts import render, get_object_or_404
from django.shortcuts import render, redirect
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib import messages
from django.contrib.auth.views import LoginView
from django.contrib.auth import login, logout
from django.urls import reverse
from django.utils import timezone
from django.http import HttpResponse
from django.template.loader import get_template

from gestion_almacenes import models
from gestion_almacenes.models import Pedido, PedidoProducto, ProductoPosicion

from .models import Producto, Pedido, Cliente
from .models import Producto, Posicion
from .models import Proveedor
from .models import Pedido, PedidoProducto

from .forms import FiltroProveedorForm, ClienteCreationForm
from .forms import FiltroProveedorForm
from .forms import PedidoFilterForm
from .forms import FiltroProveedorForm

from .utils import pedir_proveedores, migrations_picstock, product_type
from xhtml2pdf import pisa

from datetime import timedelta
from django.utils import timezone

class ClienteLoginView(LoginView):
    template_name = 'login.html'
    def get_success_url(self):
        return reverse('home')


def register(request):
    if request.method == 'POST':
        form = ClienteCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('home')
    else:
        form = ClienteCreationForm()
    return render(request, 'register.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('home')

def index(request):
    # Obtener los proveedores directamente de los objetos Producto
    proveedores = Proveedor.objects.values_list('nombre_proveedor', flat=True).distinct()

    form = FiltroProveedorForm(proveedores)
    productos = Producto.objects.all()

    if request.method == 'POST':
        form = FiltroProveedorForm(proveedores, request.POST)
        if form.is_valid():
            proveedor_seleccionado = form.cleaned_data['proveedor']
            if proveedor_seleccionado:
                productos = productos.filter(proveedor__nombre_proveedor=proveedor_seleccionado)

    productos_modificados = []

    for producto in productos:
        referencia_modificada = producto.referencia.split('_')[0].capitalize()

        if referencia_modificada == 'Pinta':
            referencia_modificada = 'Pintalabios'

        if referencia_modificada == 'Locion':
            referencia_modificada = 'Loción'

        if referencia_modificada == 'Cosmetico':
            referencia_modificada = 'Cosmético'

        producto_dict = {
            'referencia': producto.referencia,
            'referencia_mod': referencia_modificada,
            'proveedor': producto.proveedor,
            'cantidad_stock': producto.cantidad_stock,
            'peso_por_unidad': producto.peso_por_unidad,
        }
        productos_modificados.append(producto_dict)

    return render(request, 'index.html', {'productos': productos_modificados, 'form': form, 'page': 'home'})


@staff_member_required
def registrar_producto(request):
    if request.method == 'POST':
        codigo = request.POST.get('codigo')
        print(codigo)
        
        pattern = r'^([A-Za-z]+)(\d+)-(\d+)-([A-Za-z]+)$'

        match = re.match(pattern, codigo)
        if match:
            type_code, number, quantity, supplier = match.groups()
            full_product_name = f'{product_type(type_code)}_{number}'
            print(f'Nombre completo del producto: {full_product_name}')
            print(f'Cantidad del producto: {quantity}')
            print(f'Proveedor del producto: {supplier}')
            quantity = int(quantity)
            nuevo_producto = Producto.objects.get(referencia = full_product_name)
            nuevo_producto.cantidad_stock = nuevo_producto.cantidad_stock + quantity
            nuevo_producto.save()
            posiciones = ProductoPosicion.objects.filter(producto = nuevo_producto).order_by("posicion")
            posicion_picking = Posicion.objects.get(id = posiciones[0].posicion.id)
            posicion_stock = Posicion.objects.get(id = posiciones[1].posicion.id)
            if posicion_picking.unidades_ocupadas < 20:
                cantidad_restante = 20 - posicion_picking.unidades_ocupadas
                posicion_picking.unidades_ocupadas = posicion_picking.unidades_ocupadas + cantidad_restante
                cantidad_restante = quantity - cantidad_restante
                posicion_stock.unidades_ocupadas = posicion_stock.unidades_ocupadas + cantidad_restante
                posicion_picking.save()
                posicion_stock.save()
                messages.success(request, f'Se han añadido {quantity} unidades de {full_product_name} al sistema')
                return redirect('/admin')
            else:
                posicion_stock.unidades_ocupadas = posicion_stock.unidades_ocupadas + quantity
                posicion_stock.save()
                messages.success(request, f'Se han añadido {quantity} unidades de {full_product_name} al sistema')
                return redirect('/admin')
        else:
            print('El código proporcionado no coincide con el patrón esperado.')
            messages.error(request, f'El codigo proporcionado no sigue el formato esperado')
    return render(request, "registrar_producto.html")


def producto_detail(request, id):
    producto = get_object_or_404(models.Producto, referencia=id)
    nombre_referencia = producto.referencia.split('_')[0].capitalize()
    return render(request, "product_detail.html", {'producto': producto, 'nombre': nombre_referencia})

def anadirAcesta(request, id):
    producto = get_object_or_404(models.Producto, referencia=id)
    referencia = producto.referencia
    nombre_referencia = producto.referencia.split('_')[0].capitalize()
    
    if request.method == 'POST':
        cantidad = int(request.POST.get('cantidad', 0))
        
        if cantidad > producto.cantidad_stock:
            return redirect(f'/product_detail/{producto.id}/')  # Redirige al usuario a la página de detalle del producto
        else:
            carrito = request.session.get('carrito', {})
            carrito[producto.id] = {'referencia': referencia, 'cantidad': cantidad}
            request.session['carrito'] = carrito
            messages.success(request, f'{cantidad} unidades de {nombre_referencia} han sido añadidas al carrito')
            return redirect('home')
    else:
        messages.error(request, f'Sólo hay {producto.cantidad_stock} unidades disponibles')
        return render(request, "product_detail.html", {'producto': producto, 'nombre': nombre_referencia})



def checkout(request):
    carrito = request.session.get('carrito', {})
    productos = []
    total = 0
    for id, item in carrito.items():
        producto = get_object_or_404(models.Producto, id=id)
        precio = producto.precio
        subtotal = precio * item['cantidad']
        total += subtotal
        productos.append({
            'id': producto.id,
            'nombre': producto.referencia,
            'producto': producto,
            'cantidad': item['cantidad'],
            'precio': precio,
            'subtotal': subtotal,
        })

    context = {
        'productos': productos,
        'total': total,
        'page': 'carrito'
    }
    return render(request, 'checkout.html', context)


from django.contrib.auth.decorators import login_required

@login_required
def procesar_compra(request):
    if request.method == 'POST':
        carrito = request.session.get('carrito', {})
        unidadesTotales = 0
        pesoTotal = 0
        productos = []
        total = 0
        entrega = ''
        for id, item in carrito.items():
            try:
                producto = Producto.objects.get(id=id)
                if producto.cantidad_stock < item['cantidad']:
                    messages.error(request, f"No hay suficientes unidades en stock para el producto '{producto.referencia}'.")
                    return redirect('/checkout/')
                productos.append({
                    'producto': producto,
                    'cantidad': item['cantidad'],
                })
                producto.cantidad_stock -= item['cantidad']
                producto.save()
            except Producto.DoesNotExist:
                raise ValueError(f"No se encontró el producto con ID '{id}'.")
        
        tipo_envio = request.POST.get('tipo_envio')
        agencia_transporte = request.POST.get('agencia_transporte')
        print(tipo_envio)
        cliente = Cliente.objects.get(id=request.user.id)

        pedido = Pedido.objects.create(
            cliente=cliente,
            fecha_hora_pedido=timezone.now(),
            tipo_envio=tipo_envio,
            agencia_transporte=agencia_transporte,
        )

        print(pedido.id)
        for id, item in carrito.items():
            producto = Producto.objects.get(id=id)
            cantidad = item['cantidad']
            unidadesTotales = unidadesTotales + cantidad
            
            pedidoproducto = PedidoProducto.objects.create(
                pedido = pedido,
                producto = producto,
                cantidad = cantidad,
            )
           
        print(pedido.agencia_transporte)
        
        cliente = request.user
        
       # Genera el PDF y guárdalo en el servidor
        output_dir = os.path.join(settings.MEDIA_ROOT, 'etiquetas')
        os.makedirs(output_dir, exist_ok=True)
        filename = f"Comprobante_{cliente.nombre_cliente}_{timezone.now().strftime('%Y-%m-%d_%H-%M-%S')}.pdf"
        output_path = os.path.join(output_dir, filename)

        if pedido.agencia_transporte == "DHL":
            pdf = generar_pdf('comprobanteDHL.html', {'cliente': cliente, 'pedido': pedido, 'productos': productos }, output_path)
        

gestion_almacenes/templates/admin_custom.html
<!-- miapp/templates/miapp/admin_dashboard.html -->
{% extends "admin/base.html" %}

{% block extrastyle %}
{{ block.super }}
<!-- Agrega aquí estilos adicionales si es necesario -->
{% endblock %}

{% block content %}

<div id="content-main">
    <h1>Bienvenido al panel de administración</h1>
    <h2>Tablas</h2>
    <ul>
        <!-- Agrega un enlace a cada tabla/modelo aquí -->
        <li><a href="{% url 'admin:gestion_almacenes_proveedor_add' %}">Agregar Proveedor</a>
        </li>
    </ul>
    <h2>Opciones de gestión</h2>
    <ul>
        <li><a href="{% url 'registrar_producto' %}">Registrar producto</a></li>
        <!-- Agrega un enlace a la nueva página de visualización -->
        <li><a href="{% url 'admin:pedidos_productos' %}">Ver pedidos y productos</a></li>
    </ul>
</div>
{% endblock %}

gestion_almacenes/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon" />
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'navbar.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz4fnFO9gybBud7l3x7tS8Gw/xj5l6uS/6i62E6G4b6db7U6J4Q25Dbg" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-KyZXEAg3QhqLMpG8r+Knujsl5/Vfzoc+XJd+hwvJg+vkK/uxreDwF1O1V7Kd9Ktm" crossorigin="anonymous"></script>

</head>
<body>
    {%include 'navbar.html'%}
    <div class="container-fluid">
        {% include 'messages.html' %}
        {% block content1 %}{% endblock %}
    </div>
    {% block content %}{% endblock %}
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</html>

gestion_almacenes/templates/checkout.html
{% extends 'base.html' %}
{% block title %}Checkout{% endblock %}
{% block content %}
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">

<div class="container">
  <h1 class="text-center mb-4">Checkout</h1>
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>Referencia</th>
        <th>Producto</th>
        <th>Precio unitario</th>
        <th>Cantidad</th>
        <th>Subtotal</th>
        <th>Acciones</th>
      </tr>
    </thead>
    <tbody>
      {% for producto in productos %}
      <tr>
        <td>{{ producto.id }}</td>
        <td>{{ producto.nombre }}</td>
        <td>{{ producto.precio }} €</td>
        <td>{{ producto.cantidad }}</td>
        <td>{{ producto.subtotal }} €</td>
        <td>
          <form method="post" action="{% url 'eliminar_producto' producto.id %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Eliminar</button>
          </form>
        </td>
      </tr>
      {% endfor %}
    </tbody>
    <tfoot>
      <tr>
        <td colspan="4" style="text-align: right;">Total:</td>
        <td>{{ total }} €</td>
        <td></td>
      </tr>
    </tfoot>
  </table>
  </div>
<form method="post" action="{% url 'procesar_compra' %}">
    {% csrf_token %}
    <div class="text-center">
      <h4>Tipo de envío:</h4>
      <div class="btn-group btn-group-toggle mb-4" data-toggle="buttons">
        <label class="btn btn-secondary active">
          <input type="radio" name="tipo_envio" id="option1" autocomplete="off" value="EST" checked>Estándar
        </label>
        <label class="btn btn-secondary">
          <input type="radio" name="tipo_envio" id="option2" autocomplete="off" value="URG">Urgente
        </label>
      </div>

      <h4>Transportista:</h4>
      <div class="btn-group btn-group-toggle mb-4" data-toggle="buttons">
        <label class="btn btn-secondary active">
          <input type="radio" name="agencia_transporte" id="option1" autocomplete="off" value="DHL" checked>DHL
        </label>
        <label class="btn btn-secondary">
          <input type="radio" name="agencia_transporte" id="option2" autocomplete="off" value="COR">Correos
        </label>
        <label class="btn btn-secondary">
          <input type="radio" name="agencia_transporte" id="option2" autocomplete="off" value="SEU">Seur
        </label>
      </div>
      <div>
        <button class="btn btn-primary" type="submit">Comprar</button>
      </div>
    </div>
  </form>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

<style>

  
  {% comment %} .container {
    max-width: 800px;
    margin: auto;
  }
   {% endcomment %}
  table {
    width: 100%;
    border-collapse: collapse;
    margin-bottom: 2rem;
  }
  
  th,
  td {
    padding: 0.75rem;
    vertical-align: middle;
    text-align: center;
  }
  
  thead {
    background-color: #f8f9fa;
    font-weight: bold;
  }
  
  tbody tr:nth-of-type(even) {
    background-color: #f8f9fa;
  }
  
  tfoot tr:nth-of-type(1) {
    background-color: #e9ecef;
    font-weight: bold;
  }
  
  tfoot tr:nth-of-type(2) {
    background-color: #e9ecef;
    font-weight: bold;
  }
  
  tfoot tr:nth-of-type(3) {
    background-color: #e9ecef;
    font-weight: bold;
  }
  
  
  /* Estilos para los nuevos campos */
  tfoot td[colspan="4"] {
    text-align: right;
  }
  
  tfoot td[colspan="1"] {
    text-align: left;
  }   

  {% endblock %}

gestion_almacenes/templates/comprobanteCorreos.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Comprobante de Compra</title>
    <style>
        body {
            font-family: Arial, sans-serif;
        }
        table {
            width: 100%;
            max-width: 600px;
            border-collapse: collapse;
            margin: 0 auto;
        }
        th, td {
            padding: 1px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }
        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        h1, h2 {
            text-align: center;
        }
        .col-ref {
            width: 15%;
        }
        .col-prod {
            width: 35%;
        }
        .col-precio,
        .col-cantidad,
        .col-subtotal {
            width: 16.666%;
        }
    </style>
</head>
<body>
    <h1>Comprobante de Compra</h1>
    <h2>Pedido solicitado a Correos:</h2>

    <p>Día y hora: {{ pedido.fecha_hora_pedido }}</p>
    <p>Tipo de pedido: {{ pedido.tipo_envio }}</p>
    <p>ID de pedido: {{ pedido.id }}</p>
    <p>Nombre del cliente: {{ cliente.nombre_cliente }}</p>
    <p>Dirección del cliente: {{ cliente.direccion_cliente }}</p>
    <p>Código postal: {{ cliente.codigo_postal }}</p>
    <p>Peso total: {{ pesoTotal }} Kg</p>
    <p>Cantidad total de productos: {{ unidadesTotales }}</p>

</body>
</html>

gestion_almacenes/templates/comprobanteDHL.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Comprobante de Compra</title>
    <style>
        body {
            font-family: Arial, sans-serif;
        }
        table {
            width: 100%;
            max-width: 600px;
            border-collapse: collapse;
            margin: 0 auto;
        }
        th, td {
            padding: 1px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }
        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        h1, h2 {
            text-align: center;
        }
        .col-ref {
            width: 15%;
        }
        .col-prod {
            width: 35%;
        }
        .col-precio,
        .col-cantidad,
        .col-subtotal {
            width: 16.666%;
        }
    </style>
</head>
<body>
    <h1>Comprobante de Compra</h1>
    <h2>Pedido solicitado a DHL:</h2>
    <p>ID de pedido: {{ pedido.id }}</p>
    <p>Día y hora: {{ pedido.fecha_hora_pedido }}</p>
    <p>Tipo de pedido: {{ pedido.tipo_envio }}</p>
    <p>Nombre del cliente: {{ cliente.nombre_cliente }}</p>
    <p>Dirección del cliente: {{ cliente.direccion_cliente }}</p>

    <h2>Artículos:</h2>
    <table>
        <thead>
            <tr>
                <th class="col-ref">Referencia</th>
                <th class="col-cantidad">Cantidad</th>
            </tr>
        </thead>
        <tbody>
            {% for item in productos %}
            <tr>
                <td class="col-ref">{{ item.producto.referencia }}</td>
                <td class="col-cantidad">{{ item.cantidad }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

gestion_almacenes/templates/comprobanteSeur.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Comprobante de Compra</title>
    <style>

    </style>
</head>
<body>
    <h1>Comprobante de Compra</h1>
    <h2>Pedido solicitado a Seur:</h2>

    <p>Día de entrega: {{ entrega }}</p>
    <p>Tipo de pedido: {{ pedido.tipo_envio }}</p>
    <p>ID de pedido: {{ pedido.id }}</p>
    <p>Nombre del cliente: {{ cliente.nombre_cliente }}</p>
    <p>Dirección del cliente: {{ cliente.direccion_cliente }}</p>
    <p>Peso total: {{ pesoTotal }} Kg</p>


</body>
</html>

gestion_almacenes/templates/login.html
{% extends 'base.html' %}

{% block content %}

{% load myfilters %}
  <main class="container form-signin w-100 m-auto">
    <form method="post">
    {% csrf_token %}
    <h1 class="h3 mb-3 fw-normal">Iniciar sesion</h1>
    {{ form.non_field_errors }}
  
      <div class="form-floating mb-3">
        {{form.username|addclass:'form-control'}}
        {{form.username.label_tag}}
        {{ form.username.errors }}
      </div>
      <div class="form-floating mb-3">
        {{form.password|addclass:'form-control'}}
        {{form.password.label_tag}}
        {{ form.password.errors }}
        <span class="helptext">{{ form.password.help_text }}</span>
      </div>
      <button class="w-100 btn btn-lg btn-primary" type="submit">Iniciar sesion</button>
    </form>
    <p><a href="{% url 'register' %}">Registrate aqui</a></p>
  </main>
{% endblock %}

gestion_almacenes/templates/pedidos_productos.html
{% extends "admin/base.html" %}

{% block content %}
<h1>Pedidos y productos</h1>

<!-- Formulario de búsqueda -->
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Buscar</button>
</form>

<table>
    <tr>
        <th>Pedido</th>
        <th>Producto</th>
        <th>Posición</th>
    </tr>
    {% for pedido_productos in pedidos_productos_list %}
        {% for producto in pedido_productos.productos %}
            <tr>
                <td>{{ pedido_productos.pedido }}</td>
                <td>{{ producto.producto }}</td>
                <td>{{ producto.producto.productoposicion_set.first.posicion }}</td>
            </tr>
        {% endfor %}
    {% endfor %}
</table>
{% endblock %}